# Copyright 2017 Chi-Hung Weng
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# This Dockerfile builds a Deep Learning & Python3 environment covering:
# Keras, Tensorflow and OpenCV.
#
# WARNING: TensorFlow built by this image supports CPU instructions
# such as SSE4.1, SSE4.2, AVX, AVC2, FMA. If these instructions are 
# not supported by your CPU, please do not use this Dockerfile.
#
# This file modifies a Dockerfile that is originally 
# maintained by the TensorFlow Authors (see the link below).
# https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/Dockerfile.devel-gpu

FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04

MAINTAINER Chi-Hung Weng <wengchihung@gmail.com>

# Specify number of CPUs can be used while building Tensorflow and OpenCV.
ARG NUM_CPUS_FOR_BUILD=40

# Specify the version of Bazel.
ARG BAZEL_VER=0.6.1

# Specify the version of Tensorflow. I've tested the state 9ff05e9,
# which is newer than the v1.3.1 build.
ARG TF_VER=9ff05e9

# Specify the version of OpenCV. I've chosen the state af8ed9d (v3.3.0-dev), 
# as with the v3.3.0 build the newest GPU arch ( i.e. compute capability 7.0)
# cannot be detected by default.
ARG OPENCV_VER=af8ed9d

RUN apt update && apt install -y --no-install-recommends \
        build-essential \
        curl \
        git \
        libcurl3-dev \
        libfreetype6-dev \
        libpng12-dev \
        libzmq3-dev \
        pkg-config \
        python3-dev \
        python \
        rsync \
        software-properties-common \
        unzip \
        zip \
        zlib1g-dev \
        openjdk-8-jdk \
        openjdk-8-jre-headless \
        wget \
        qt4-default \
        apt-utils \
        cmake \
        libgtk2.0-dev \
        libavcodec-dev \
        libavformat-dev \
        libswscale-dev \
        libtbb2 \
        libtbb-dev \
        libjpeg-dev \
        libpng-dev \
        libtiff-dev \
        libjasper-dev \
        libdc1394-22-dev \
        && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*
    
# Get pip for Python3.
RUN curl -fSsL -O https://bootstrap.pypa.io/get-pip.py && \
    python3 get-pip.py && \
    rm get-pip.py
    
# Install some useful and deep-learning-related packages for Python3.
RUN pip3 --no-cache-dir install \
         h5py \
         jupyter \
         matplotlib \
         numpy \
         pandas \
         seaborn \
         scipy \
         sklearn \
         scikit-image

# Set up our notebook config.
RUN mkdir /root/.jupyter && \
    cd /root/.jupyter && \
    wget https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/tools/docker/jupyter_notebook_config.py

# Jupyter has issues with being run directly:
#   https://github.com/ipython/ipython/issues/7062
# We just add a little wrapper script.
RUN cd / && \
    wget https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/tools/docker/run_jupyter.sh && \
    chmod +x run_jupyter.sh

# Set up Bazel
# Running bazel inside a `docker build` command causes trouble, cf:
#   https://github.com/bazelbuild/bazel/issues/134
# The easiest solution is to set up a bazelrc file forcing --batch.
RUN echo "startup --batch" >>/etc/bazel.bazelrc
# Similarly, we need to workaround sandboxing issues:
#   https://github.com/bazelbuild/bazel/issues/418
RUN echo "build --spawn_strategy=standalone --genrule_strategy=standalone" \
    >>/etc/bazel.bazelrc
# Install Bazel.
WORKDIR /
RUN mkdir /bazel && \
    cd /bazel && \
    curl -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36" -fSsL -O https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VER}/bazel-${BAZEL_VER}-installer-linux-x86_64.sh && \
    curl -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36" -fSsL -o /bazel/LICENSE.txt https://raw.githubusercontent.com/bazelbuild/bazel/master/LICENSE && \
    chmod +x bazel-*.sh && \
    ./bazel-${BAZEL_VER}-installer-linux-x86_64.sh && \
    cd / && \
    rm -f /bazel/bazel-${BAZEL_VER}-installer-linux-x86_64.sh

# Download the TensorFlow source folder from Github.
RUN cd /opt && git clone https://github.com/tensorflow/tensorflow.git && \
    cd tensorflow && \
    git checkout ${TF_VER}
WORKDIR /opt/tensorflow

# Configure the build (CUDA9, cuDNN7, Python3, etc).
ENV CI_BUILD_PYTHON=python3 \
    LD_LIBRARY_PATH=/usr/local/cuda/extras/CUPTI/lib64:${LD_LIBRARY_PATH} \
    TF_NEED_CUDA=1 \
    TF_CUDA_COMPUTE_CAPABILITIES=3.0,3.5,5.2,6.0,6.1,7.0 \
    TF_CUDA_VERSION=9.0 \
    TF_CUDNN_VERSION=7 \
    CUDNN_INSTALL_PATH=/usr/lib/x86_64-linux-gnu \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/local/lib/python3.5/dist-packages \
    TF_NEED_JEMALLOC=1 \
    TF_NEED_GCP=0 \
    TF_NEED_HDFS=0 \
    TF_ENABLE_XLA=1 \
    TF_NEED_GDR=0 \
    TF_NEED_VERBS=0 \
    TF_NEED_OPENCL=0 \
    TF_NEED_MPI=0

# Build and install Tensorflow.
# Also, Keras will be installed when the installation of Tensorflow is complete.
RUN mkdir -p /usr/local/nvidia/lib64/ && \
    cp /usr/local/cuda-9.0/targets/x86_64-linux/lib/stubs/libcuda.so /usr/local/nvidia/lib64/libcuda.so.1 && \
    tensorflow/tools/ci_build/builds/configured GPU && \
    bazel build -c opt \
                --copt=-msse4.1 \
                --copt=-msse4.2 \
                --copt=-mavx \
                --copt=-mavx2 \
                --copt=-mfma \
                --copt=-O3 \
                --config=cuda \
                --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" \
                --jobs=${NUM_CPUS_FOR_BUILD} \
                tensorflow/tools/pip_package:build_pip_package && \
    bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/pip && \
    pip3 --no-cache-dir install --upgrade /tmp/pip/tensorflow-*.whl && \
    pip3 --no-cache-dir install keras && \
    rm -rf /tmp/pip && \
    rm -rf /root/.cache
# Clean up pip wheel and Bazel cache when done.

# Install OpenCV 3 
RUN git clone https://github.com/opencv/opencv.git /root/opencv && \
    cd /root/opencv && \
    git checkout ${OPENCV_VER} && \
    mkdir build && \
    cd build && \
    cmake -D WITH_TBB=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_V4L=ON -D INSTALL_C_EXAMPLES=OFF -D INSTALL_PYTHON_EXAMPLES=OFF -D BUILD_EXAMPLES=OFF -D WITH_QT=ON -D WITH_OPENGL=ON -D ENABLE_FAST_MATH=1 -D CUDA_FAST_MATH=1 -D WITH_CUBLAS=1 .. && \
    make -j"${NUM_CPUS_FOR_BUILD}" && \
    make install && \
    ldconfig && \
    rm -rf /root/opencv
# The source folder of OpenCV 3 is too big. We remove it after the installation.

RUN mkdir /notebooks && \
    wget -O /notebooks/MNISTDemoKeras.ipynb https://raw.githubusercontent.com/chi-hung/PythonTutorial/master/code_examples/KerasMNISTDemo.ipynb
WORKDIR /notebooks

# TensorBoard
EXPOSE 6006
# IPython
EXPOSE 8888

CMD ["/run_jupyter.sh", "--allow-root"]
#RUN ["/bin/bash"]