FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04

MAINTAINER Chi-Hung Weng <wengchihung@gmail.com>

ARG NUM_CPUS_FOR_BUILD=4
ARG OPENCV_VER=af8ed9d

RUN apt update && apt install -y --no-install-recommends \
        build-essential \
        curl \
        git \
        libcurl3-dev \
        libfreetype6-dev \
        libpng12-dev \
        libzmq3-dev \
        pkg-config \
        python3-dev \
        python3-setuptools \
        rsync \
        software-properties-common \
        unzip \
        zip \
        zlib1g-dev \
        wget \
        qt4-default \
        apt-utils \
        cmake \
        libgtk2.0-dev \
        libavcodec-dev \
        libavformat-dev \
        libswscale-dev \
        libtbb2 \
        libtbb-dev \
        libjpeg-dev \
        libpng-dev \
        libtiff-dev \
        libjasper-dev \
        libdc1394-22-dev \
        libopenblas-dev \
        liblapack-dev \
        graphviz \
        && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*
    
# Get pip for Python3.
RUN curl -fSsL -O https://bootstrap.pypa.io/get-pip.py && \
    python3 get-pip.py && \
    rm get-pip.py
    
# Install some useful and deep-learning-related packages for Python3.
RUN pip3 --no-cache-dir install \
         h5py \
         jupyter \
         matplotlib \
         numpy \
         pandas \
         seaborn \
         scipy \
         sklearn \
         scikit-image

# Set up our notebook config.
RUN mkdir /root/.jupyter && \
    cd /root/.jupyter && \
    wget https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/tools/docker/jupyter_notebook_config.py

# Jupyter has issues with being run directly:
#   https://github.com/ipython/ipython/issues/7062
# We just add a little wrapper script.
RUN cd / && \
    wget https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/tools/docker/run_jupyter.sh && \
    chmod +x run_jupyter.sh
    
# Install OpenCV 3 
RUN git clone https://github.com/opencv/opencv.git /root/opencv && \
    cd /root/opencv && \
    git checkout ${OPENCV_VER} && \
    mkdir build && \
    cd build && \
    cmake -D WITH_TBB=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_V4L=ON -D INSTALL_C_EXAMPLES=OFF -D INSTALL_PYTHON_EXAMPLES=OFF -D BUILD_EXAMPLES=OFF -D WITH_QT=ON -D WITH_OPENGL=ON -D ENABLE_FAST_MATH=1 -D CUDA_FAST_MATH=1 -D WITH_CUBLAS=1 .. && \
    make -j${NUM_CPUS_FOR_BUILD}  && \
    make install && \
    ldconfig && \
    rm -rf /root/opencv
# The source folder of OpenCV 3 is too big. We remove it after the installation.

RUN git clone --recursive https://github.com/dmlc/mxnet /opt/mxnet

WORKDIR /opt/mxnet

# Build and Install MXNET.
RUN make -j${NUM_CPUS_FOR_BUILD} USE_OPENCV=1 \
                                 USE_BLAS=openblas \
                                 USE_CUDA=1 \
                                 USE_CUDA_PATH=/usr/local/cuda \
                                 USE_CUDNN=1
RUN cd python && python3 setup.py install

# Install Keras for MXNET.
RUN pip3 --no-cache-dir install keras-mxnet

RUN mkdir /notebooks && \
    wget -O /notebooks/KerasMNISTDemoMXNET.ipynb https://raw.githubusercontent.com/chi-hung/PythonTutorial/master/code_examples/KerasMNISTDemoMXNET.ipynb
WORKDIR /notebooks

# IPython
EXPOSE 8888

CMD ["/run_jupyter.sh", "--allow-root"]
#RUN ["/bin/bash"]
